title = "Yquan Blogs"
baseURL = "http://www.yquan.win/"
languageCode = "zh-CN"
theme = "bootie-docs"


googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
[params]
    copyright = "Copyright (c) 2017-2019, yquan; All rights reserved. 赣ICP备18007084号"
    description = "积累与运用。"
    footer = "R语言爱好者，生信分析，Python shell JS，热衷于写shiny app可重复分析的小工具"
    searchDomain = "yquan.win"  # google 搜索
    # options for highlight.js (version, additional languages, and theme)
    highlightStyle = "github"
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

[params.icon]
url = "favicon.jpg" 

[permalinks]
    post = "/:year/:month:day:slug/"

[[menu.main]]
    weight = 3
    name = "计划"
    url = "/project/"
[[menu.main]]
    weight = 4
    name = "关于"
    url = "/about/"

